name: FranklinGin
favicon: null
layout_spectrum: 0.12048679660074413
typography_spectrum: 0.7631892575882375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6874004376586527
  lightness: 0.9485249409917742
  saturation: 0.4399801092222333
  rhythmicContrast: 0.8714427987579256
purpose: []
